@startuml

title Round Robin Scheduling

activate Scheduler
Scheduler -> "Task A": start
note left
Der Scheduler startet einen Prozess und lässt ihn für eine definierte Zeit laufen.
end note
deactivate Scheduler
activate "Task A"
...
Scheduler -> "Task A": stop
note left: Wenn die Zeit abgelaufen ist, wird der Prozess gestoppt...
deactivate "Task A"

activate Scheduler
Scheduler -> "Task B": start
note left: ... und der nächste gestartet.
deactivate Scheduler
activate "Task B"
...
Scheduler -> "Task B": stop
deactivate "Task B"

activate Scheduler
Scheduler -> "Task C": start
deactivate Scheduler
activate "Task C"
...
Scheduler -> "Task C": stop
deactivate "Task C"

@enduml